language: cpp

matrix:
  include:
    - os: osx
      osx_image: osx10.11
      env: OSX=10.11
      compiler: clang
    - os: osx
      osx_image: xcode7
      env: OSX=10.10
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.2
      env: OSX=10.9
      compiler: clang
    - os: linux
      addons:
	apt:
	  packages:
	  - gfortran
	  - libblas-dev
	  - liblapack-dev
  allow_failures:
    - os: osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$OSX" != "10.9" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$OSX" != "10.9" ]]; then brew install gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$OSX" != "10.9" ]]; then brew install libblas-dev liblapack-dev; fi
  - git clone https://gist.github.com/tkralphs/13d4529b4d4e8889f3a6 scripts
  - bash scripts/get.dependencies.sh fetch > /dev/null

script: bash scripts/get.dependencies.sh build --quiet --threads=10 --with-mosek-incdir=/usr/local/mosek/7.1/tools/platform/linux64x86/h --with-mosek-lib='-L/usr/local/mosek/7.1/tools/platform/linux64x86/bin -lmosek64 -lmosekxx7_1 -lmosekjava7_1 -lmosekscopt7_1 -liomp5' --with-cplex-incdir=/usr/local/cplex/include/ilcplex --with-cplex-lib='-L/usr/local/cplex/lib/x86-64_linux/static_pic/ -lcplex -lm -lpthread'
